name = "wp-github-release-api"
main = "index.js"
compatibility_date = "2025-04-15"
workers_dev = true
account_id = ""
route = { pattern = "*hiive.cloud/workers/release-api/*", zone_id = "" }

[[r2_buckets]]
binding = "RELEASE_API_R2_BUCKET"
bucket_name = "nfd-github-release-api"

# Staging Environment
[env.staging]
name = "wp-github-release-api-staging"
route = { pattern = "*hiive.cloud/workers/release-api-staging/*", zone_id = "" }

[[env.staging.r2_buckets]]
binding = "RELEASE_API_R2_BUCKET"
bucket_name = "nfd-github-release-api-test"

# Local development settings
[env.local]
[[env.local.r2_buckets]]
binding = "RELEASE_API_R2_BUCKET"
bucket_name = "nfd-github-release-api-test"
preview_bucket_name = "nfd-github-release-api-test"